### ISSUE TITLE
brief4vscode.cut (and others) not found...

### ISSUE THREAD

**Issue by KIT-GregC** [ralphkw1/brief4vscode#1]
Hi,
   Straight off the bat, thanks for doing this. Let me know how I can compensate you! I use Visual SlickEdit on my home computers but stuck with vscode at work. I really think it's a great tool, but brief emulation is amongst the features I miss from Slickedit.
   
   I turn out to be that guy that tries this on a mac. If I hit home, end, etc, I get "brief4vscode.<blah>" not found. 
   The extension got installed into the .vscode area. I looked in the javascript and it "appeared ok" at a glance. I wonder what could be wrong. I'll include a screenshot of the files as they lay on the mac. 
   

  
<img width="898" alt="Screen Shot 2022-02-09 at 22 49 13" src="https://user-images.githubusercontent.com/92070971/153214543-41625aca-8c3e-4fff-84b2-1002e7f8a5b9.png">

**Comment by ralphkw1** [comment]
> Hi, Straight off the bat, thanks for doing this. Let me know how I can compensate you! I use Visual SlickEdit on my home computers but stuck with vscode at work. I really think it's a great tool, but brief emulation is amongst the features I miss from Slickedit.
> 
> I turn out to be that guy that tries this on a mac. If I hit home, end, etc, I get "brief4vscode." not found. The extension got installed into the .vscode area. I looked in the javascript and it "appeared ok" at a glance. I wonder what could be wrong. I'll include a screenshot of the files as they lay on the mac.
> 
> <img alt="Screen Shot 2022-02-09 at 22 49 13" width="898" src="https://user-images.githubusercontent.com/92070971/153214543-41625aca-8c3e-4fff-84b2-1002e7f8a5b9.png">

Sorry about the delay. No compensation necessary. I do these plugin's just for fun.
Unfortunately, I know nothing about the Mac, don't own one and don't have access to one. So difficult to understand the issue or help. May be some kind of file ownership or security issue? I don't own any software certificates so maybe the mac doesn't like running unsigned code.
Of course, feel free to create a plugin project in VSCode on your mac, then cut and paste the code. You could start with a single command and see if it exhibits the same issue.
Best Regards,
Ralph
