### ISSUE TITLE
HOME and END key differences

### ISSUE THREAD

**Issue by jevers76** [ralphkw1/brief4vscode#2]
I am enjoying using this extension, but my finger muscle memory is often getting different than expected results when using the HOME (and END) key(s).  The first HOME keypress should take the cursor to the beginning of the current line even if the cursor is already at the beginning of the line.  In breif4vscode the first HOME keypress when already at the beginning of the line will treat this like a second keypress and go to the top of the page.  Similar action with the END key.

I found a windows version of brief at briefeditor.com

**Comment by rkdawenterprises** [comment]
> 



> I am enjoying using this extension, but my finger muscle memory is often getting different than expected results when using the HOME (and END) key(s). The first HOME keypress should take the cursor to the beginning of the current line even if the cursor is already at the beginning of the line. In breif4vscode the first HOME keypress when already at the beginning of the line will treat this like a second keypress and go to the top of the page. Similar action with the END key.
> 
> I found a windows version of brief at briefeditor.com

I understand your point. This functionality is not documented well in the Brief documentation, namely the time delay between 'home' keystrokes that imply 'home' vs. 'home-home' vs. 'home-home-home'. This would require introducing a timer, which I don't know is worth the effort. I mean if your cursor is already at home, why hit home again? Regardless, I don't mind investigating this and putting in a configuration option to change the behavior.

**Comment by ralphkw1** [comment]
I looked into this and although your issue has merit and should be implemented, I do not think I can justify the effort vs. the impact to the codebase.
There are at least two methods to attempt to implement this, 1) the one you suggested, namely counting home/end commands and clearing for any other command, and 2) a timer. Notice I said "commands" not keystrokes. Extensions in VSCode and not privy to keystrokes. They can only request a command be registered with a given key combination. So I would have to register all keystrokes (removing any conflicting "when" conditionals) and the "type" command an place code in all of these to clear the home and end count. Or do a timer, which in itself is problematic (what should the timeout be that anyone would be happy with).
Anyway thanks for the suggestion and sorry I cannot implement it.
