### ISSUE TITLE
Line marking mode disable does not clear current lines marked

### ISSUE THREAD

**Issue by greglox** [ralphkw1/brief4vscode#3]
When using Alt+L to mark lines, pressing another Alt+L does disable the line marking mode, but the current marked lines (highlighted lines) are not cleared until an arrow key is pressed.

My experience with CRISP is that pressing one Alt+L will mark the line and pressing another Alt+L will unmark the line.  The experience in brief4vscode is different in that the line is not actually unmarked.

When doing the same using the column marking (Alt+C), pressing another Alt+C (to disable) will clear the marked column.

**Comment by greglox** [comment]
In addition, this specific behavior is odd:
- Press Alt+L to enable line marking (for instance on line 10)
- Press the down arrow (a few times, bringing the cursor to line 13, with lines 10-12 marked)
- Press Alt+L to disable line marking (cursor is on line 13. lines 10-12 are still highlighted...the above issue)
- Press the up arrow will bring the cursor to line 9.  ** I would expect the cursor to move to line 12. **  Maybe this will be fixed when the issue is resolved.

**Comment by ralphkw1** [comment]
> In addition, this specific behavior is odd:
> 
> * Press Alt+L to enable line marking (for instance on line 10)
> * Press the down arrow (a few times, bringing the cursor to line 13, with lines 10-12 marked)
> * Press Alt+L to disable line marking (cursor is on line 13. lines 10-12 are still highlighted...the above issue)
> * Press the up arrow will bring the cursor to line 9.  ** I would expect the cursor to move to line 12. **  Maybe this will be fixed when the issue is resolved.

I recall not removing the existing selection in the marking modes for a reason. Unfortunately I don't remember why :-) Regardless, I updated the code to remove the selection when a marking mode is disabled. I hope it doesn't break anything else. Fix will be in v1.3.0 when published.
Regarding the cursor moving up, this is normal for VSCode. Anytime you have a selection and click the up arrow key, the cursor will move to the line above the current selection.

**Comment by ralphkw1** [comment]
Fixed in v1.3.0.

**Comment by greglox** [comment]
Thank you for the quick response and the explanation of the 'odd behavior'.
Is there any chance that the Alt+A to start a marking area could be implemented?  I see that Alt+A is associated with 'Align', but I am unfamiliar with the align function...and don't know if your keymapping can replace existing.
I am new to VSC and appreciate the Brief keybindings.
I am not sure if you will receive this and will add it to the 'issues' list next week if I don't hear a response.
Thanks,
Greg
    On Wednesday, February 14, 2024 at 04:54:20 PM CST, Ralph Williamson ***@***.***> wrote:  
 
 


Closed #3 as completed.

**Comment by ralphkw1** [comment]
> Thank you for the quick response and the explanation of the 'odd behavior'. Is there any chance that the Alt+A to start a marking area could be implemented?  I see that Alt+A is associated with 'Align', but I am unfamiliar with the align function...and don't know if your keymapping can replace existing. I am new to VSC and appreciate the Brief keybindings. I am not sure if you will receive this and will add it to the 'issues' list next week if I don't hear a response. Thanks, Greg On Wednesday, February 14, 2024 at 04:54:20 PM CST, Ralph Williamson ***@***.***> wrote: Closed #3 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Hmmm, not familiar with that one. My document says, "Noninclusive Mark. Equivalent to Mark, except that the marked area does not include the character at the end of the block". But seems easy enough. I should be able to add it, no problem.

**Comment by greglox** [comment]
Sweet! This will be a huge leap to no mouse mode!
One other thing that would be handy is using F1/F2/F3/F4 keys to goto/move/add/delete editor group windows or, at least the ALT+arrows to navigate between editor groups.  I know of the Ctrl+num to move between editor groups and that is good, but Alt+arrows would be better.  Currently the Alt+UP/Down moves the current line.
Ctrl+\ splits the editor to the right...Ctrl+Alt+\ is supposed to split the editor down, but that is not working.  Ctrl+Shift+\ is supposed to 'Split in Group', but does brace matching (which is what F11 did).

I can adapt a new method, I am just not sure how the editor group navigation is mapped.
To make the column marking 'look' better and perform the same as Brief, could you add whitespace to the end of the line while marking (you might be doing this already) so it looks like the 'virtual' window marking of Brief?  I understand that adding whitespace would modify a file, but if a file is already modified (or a configuration is set to do this) it would be able to add white-spaces, then delete the whitespaces after the marking.  Then, when placing the columnar marking, add white spaces to the left of the area of the paste.  I cannot figure out how to use the column mode as the copy and paste of a rectangular block does not make sense.  For instance:highlighting this text (copied from your readme) and 'copy' with the numpad(+):
and placing this column at line 2: column 1, looks correct as there was no missing whitespace.
But, (after an undo and) when pasting line 2: column 34 (before the 'whether'), it is wonky:
It looks like whitespaces were added when copying line 7 as they are seen at line 6 after the paste, but the pasting to line 7 is at column 3 instead of column 34.
You mentioned that virtual windows are necessary, but I think it can be solved with whitespace addition (and then deletion).
Thanks much for this extension...just trying to make it even better...
Greg





On Wednesday, February 14, 2024, 5:18 PM, Ralph Williamson ***@***.***> wrote:





Thank you for the quick response and the explanation of the 'odd behavior'. Is there any chance that the Alt+A to start a marking area could be implemented?  I see that Alt+A is associated with 'Align', but I am unfamiliar with the align function...and don't know if your keymapping can replace existing. I am new to VSC and appreciate the Brief keybindings. I am not sure if you will receive this and will add it to the 'issues' list next week if I don't hear a response. Thanks, Greg On Wednesday, February 14, 2024 at 04:54:20 PM CST, Ralph Williamson @.> wrote: Closed #3 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>


Hmmm, not familiar with that one. My document says, "Noninclusive Mark. Equivalent to Mark, except that the marked area does not include the character at the end of the block". But seems easy enough. I should be able to add it, no problem.

**Comment by ralphkw1** [comment]
I applaud your enthusiasm :-) but honestly I don't really use VSCode
any more for the last few years. So making occasional minor updates is
fine with me, But major feature additions I'm not really interested in
doing. But if you are interested, I would be more than happy to
facilitate you taking over the project. I can either add you to the
github and azure or you can just grab the source and make your own
repo and account with vscode marketplace.
I did experiment with adding spaces, but lost interest in the
complexity. The hardest part about vscode extensions is there is no
generic raw keystroke interception ability. You literally have to put
an individual key handler for every key that would affect anything.
Most of the functionality in vscode is utilizing the existing
commands. If you go to the extensions developer website, they have
pretty much all the information you need. You can contact me directly
at ***@***.***
Ralph
